---
#
- set_fact:
    start_command: "{{ oracle_wlst_create_domain_domains_home }}/{{ oracle_wlst_create_domain_info.name }}/startWebLogic.sh &"

- name: start admin server
  shell: "{{ start_command }} >> /tmp/startWebLogic.log"
  become: yes
  become_user: "{{ oracle_wslt_os_user }}"
  when: oracle_wlst_start_admin

- wait_for:
    port: {{ oracle_wlst_create_domain_info.adminserver.listen_port }}
    timeout: 800
